config/routes.rb
Tothemax::Application.routes.draw do
  root 'welcome#index'

  resources :results, :only => [:index, :show]
end

app/models/analysis_result.rb
require 'counter_hash'
require 'status_analysis'
require 'twitter_user_timeline_pager'

class AnalysisResult < ActiveRecord::Base
  include ResqueDef

  serialize :count, JSON

  resque_def(:populate_from_api) do |username|
    AnalysisResult.internal_populate_from_api(username)
  end

  def self.internal_populate_from_api(username)
    existing_result = AnalysisResult.where(:username => username).first

    existing_count = existing_result.try(:count) || {}
    most_recent_known_id = existing_result.try(:most_recent_known_id) || 0

    counter = CounterHash.new(existing_count)

    pager = TwitterUserTimelinePager.new(username)
    highest_id = pager.page_back(most_recent_known_id) do |page|
      #stringified keys needed here because of limitations of the JSON format which require keys to be strings
      counter.add(StatusAnalysis.new(page).status_length_frequency.stringify_keys)
    end

    if !existing_result
      existing_result = AnalysisResult.new
    end

    existing_result.count = counter.result
    existing_result.username = username
    existing_result.most_recent_known_id = highest_id
    existing_result.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @results = AnalysisResult.all
  end

  def show
    @result = AnalysisResult.find(params[:id])

    @chart_data = process_count_for_chart(@result.count)
  end

  private

  def process_count_for_chart(count)
    count = count.dup

    max = count.keys.map(&:to_i).max
    (1..max).each do |index|
      count[index.to_s] ||= 0
    end

    data = count.to_a.sort{|a,b| a.first.to_i <=> b.first.to_i}.map(&:second)
    labels = (1..max).to_a

    return {data: data, labels: labels}
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tothemax</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/index.html.erb
<h1>Results</h1>

<ul>
<% @results.each do |result| %>
  <li><%= link_to result.username, result_path(result.id) %>
<% end %>
</ul>

app/views/results/show.html.erb
<h1><%= @result.username %></h1>

<canvas id="count" width="1600" height="800"></canvas>

<script type="text/javascript">
  $(function() {
    var data = <%= @chart_data[:data].to_json %>
    var labels = <%= @chart_data[:labels].to_json %>

    var chartData = {
      labels: labels,
      datasets: [{
        data: data,
        fillColor: "rgba(151,187,205,0.5)",
        strokeColor : "rgba(151,187,205,1)"
      }]
    };

    var options = {
      animation: false
    }

    var context = $("#count").get(0).getContext("2d");
    var countChart = new Chart(context).Bar(chartData, options);


  });
</script>

app/views/welcome/index.html.erb
<h1>Hello.</h1>